// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdpdyjmwtgkjhupcowlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcGR5am13dGdramh1cGNvd2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MjQ0MzgsImV4cCI6MjA1ODIwMDQzOH0.ILabT0YBQmW6yztTNXn9_4Ojm5lkjPWVhgsH9lvjlMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);